version: "3.7"

services:
  db:
    image: mysql:8.0
    platform: linux/amd64
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    ports:
      - '3306:3306'
  app:
    depends_on:
      - db
    build:
      context: .
    restart: always
    env_file:
      - ./src/.env    
    volumes:
      - ./src:/app
      - /app/vendor/
      - /app/.heroku/
      - /app/.profile.d/
      - /app/.bash_history
      - /app/.composer/
    environment:
      - PORT=5000
    ports:
      - "5000:5000"
    command: sh -c 'composer install && vendor/bin/heroku-php-nginx -i app_php.ini -C app_nginx.conf'

volumes:
  db_data: